name: any_monic
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  bip32: ^1.0.7
  bitcoin_flutter: ^2.0.2
  pointycastle: ^1.0.2
  web3dart: ^1.2.3
